name: release_binary

on:
  push:
    #branches: [ action_test ]
    tags: ["v_*"]

jobs:
  make_sdist:
    runs-on: ubuntu-latest
    steps:
    - name: build_sdist
      run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
          #
          git clone https://github.com/piScope/Petra-M--RFP.git
          cd Petra-M--RFP
          #
          REF=$(echo ${GITHUB_REF#refs/heads/})
          echo "!!!!!: "$REF
          git checkout $REF
          #
          export PATH=/opt/python/cp311-cp311m/bin:$PATH

          pip3 install -U wheel six auditwheel twine build setuptools packaging
          pip3 list

          rm -rf dist/*
          python3 -m build --sdist --wheel --outdir dist/ .
          ls -l
          python3 -m twine upload --password ${{ secrets.PYPI_UPLOAD }} --username __token__ --verbose dist/*
